"""Initial Phase-1 database schema

Revision ID: 001_initial_migration
Revises: 
Create Date: 2025-01-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create agents table
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('hashed_api_token', sa.String(length=128), nullable=True),
    sa.Column('local_agent_key', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('os', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    
    # Create heartbeats table
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heartbeats_agent_id', 'heartbeats', ['agent_id'], unique=False)
    
    # Create events table
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_agent_id', 'events', ['agent_id'], unique=False)
    
    # Create applications table
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_agent_id', 'applications', ['agent_id'], unique=False)
    
    # Create app_inventory_changes table
    op.create_table('app_inventory_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('change', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create screen_time_logs table
    op.create_table('screen_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create app_usage_logs table
    op.create_table('app_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('app_name', sa.String(length=256), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_usage_logs_agent_id', 'app_usage_logs', ['agent_id'], unique=False)
    
    # Create domain_usage_logs table
    op.create_table('domain_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=512), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_usage_logs_agent_id', 'domain_usage_logs', ['agent_id'], unique=False)
    
    # Create domain_visits table
    op.create_table('domain_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_visits_agent_id', 'domain_visits', ['agent_id'], unique=False)
    
    # Create process_sessions table
    op.create_table('process_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('process', sa.String(length=512), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create merged_event_logs table
    op.create_table('merged_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merged_event_logs_agent_id', 'merged_event_logs', ['agent_id'], unique=False)
    
    # Create batch_deduplication table
    op.create_table('batch_deduplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('event_hash', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_deduplication_agent_id', 'batch_deduplication', ['agent_id'], unique=False)
    op.create_index('ix_batch_deduplication_event_hash', 'batch_deduplication', ['event_hash'], unique=True)
    
    # Create file_uploads table
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('file_base64', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    op.drop_index('ix_batch_deduplication_event_hash', table_name='batch_deduplication')
    op.drop_index('ix_batch_deduplication_agent_id', table_name='batch_deduplication')
    op.drop_table('batch_deduplication')
    op.drop_index('ix_merged_event_logs_agent_id', table_name='merged_event_logs')
    op.drop_table('merged_event_logs')
    op.drop_table('process_sessions')
    op.drop_index('ix_domain_visits_agent_id', table_name='domain_visits')
    op.drop_table('domain_visits')
    op.drop_index('ix_domain_usage_logs_agent_id', table_name='domain_usage_logs')
    op.drop_table('domain_usage_logs')
    op.drop_index('ix_app_usage_logs_agent_id', table_name='app_usage_logs')
    op.drop_table('app_usage_logs')
    op.drop_table('screen_time_logs')
    op.drop_table('app_inventory_changes')
    op.drop_index('ix_applications_agent_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_events_agent_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_heartbeats_agent_id', table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###